# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Deploy Azure Log Analytics WorkSpace"
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzConnect'
    subscriptionId: 'db2c6815-b4a2-4e70-8b36-5d3ca286b88e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'WVD-RG'
    location: 'Southeast Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'WVD-Deploy-AzureMonitor/Code/DeployLogAnalytics.json'
    csmParametersFile: 'WVD-Deploy-AzureMonitor/Parameters/WVD-PM-Deploy-LogAnalytics.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Configure HostPool For Log Analytics"
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzConnect'
    subscriptionId: 'db2c6815-b4a2-4e70-8b36-5d3ca286b88e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'WVD-RG'
    location: 'Southeast Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'WVD-Deploy-AzureMonitor/Code/DeployHostPoolDiagnostics.json'
    csmParametersFile: 'WVD-Deploy-AzureMonitor/Parameters/WVD-PM-Deploy-HostPoolDiagnostics.json'
    deploymentMode: 'Incremental'